services:
  db:
    image: mongo:7.0.5
    container_name: tokenservicedb
    ports:
      - "20000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME : "admin"
      MONGO_INITDB_ROOT_PASSWORD : "admin"